version: 0.2

env:
  shell: bash
  variables:
    TOIL_IMAGE_NAME: "toil"
    TOIL_VERSION_PREFIX: "5.8.0a1-"
    TOIL_VERSION: "bf2c046b5b1d38bdfc3043a4ea05f72db279ab64"
phases:
  pre_build:
    commands:
      - TOIL_IMAGE_URI=${TOIL_IMAGE_NAME}:${TOIL_VERSION_PREFIX}${TOIL_VERSION}
  build:
    commands:
      - docker build -t ${TOIL_IMAGE_URI} --build-arg TOIL_VERSION=${TOIL_VERSION} ./packages/engines/toil
  post_build:
    commands:
      - docker save -o toil_image.tar ${TOIL_IMAGE_URI}

artifacts:
  files:
    - toil_image.tar
